apiVersion: v1
kind: Service
metadata:
  name: acmecorp-developer-iq-git-service
spec:
  selector:
    app: acmecorp-developer-iq-git-service
  type: LoadBalancer
  ports:
  - protocol: TCP 
    port: 86
    targetPort: 86
